### ISSUE TITLE
[JENKINS-46060] JIRA plugin version 2.4.2 cannot update JIRA issues

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jira-plugin#1012]
<p>After upgrading from JIRA plugin version 2.3.1 to 2.4.2 we get the following error when trying to update JIRA issues:</p>

<pre>
09:12:51 ERROR: Step ‘JIRA: Update relevant issues’ aborted due to exception: 
09:12:51 java.lang.ClassNotFoundException: com.atlassian.fugue.Effect
09:12:51 	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
09:12:51 	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1327)
09:12:51 	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1080)
09:12:51 	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357)
09:12:51 Caused: java.lang.NoClassDefFoundError: com/atlassian/fugue/Effect
09:12:51 	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.doCreate(DefaultHttpClientFactory.java:68)
09:12:51 	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.create(DefaultHttpClientFactory.java:35)
09:12:51 	at com.atlassian.jira.<span class="code-keyword">rest</span>.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:63)
09:12:51 	at com.atlassian.jira.<span class="code-keyword">rest</span>.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
09:12:51 	at com.atlassian.jira.<span class="code-keyword">rest</span>.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
09:12:51 	at hudson.plugins.jira.JiraSite.createSession(JiraSite.java:280)
09:12:51 	at hudson.plugins.jira.JiraSite.getSession(JiraSite.java:255)
09:12:51 	at hudson.plugins.jira.Updater.perform(Updater.java:95)
09:12:51 	at hudson.plugins.jira.JiraIssueUpdater.perform(JiraIssueUpdater.java:64)
09:12:51 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
09:12:51 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
09:12:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
09:12:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
09:12:51 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
09:12:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
09:12:51 	at hudson.model.Run.execute(Run.java:1760)
09:12:51 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
09:12:51 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:12:51 	at hudson.model.Executor.run(Executor.java:405)
</pre>
<p>Downgrading to 2.3.1 solves the issue.</p>

<p>Upgrading Jenkins to version 2.60.2 also solves the issue.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kskovbo">kskovbo</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-46060" target="_blank">JIRA plugin version 2.4.2 cannot update JIRA issues</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>component(s)</b>: jira-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-08-09T10:57:34+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading from JIRA plugin version 2.3.1 to 2.4.2 we get the following error when trying to update JIRA issues:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">09:12:51 ERROR: Step ‘JIRA: Update relevant issues’ aborted due to exception: 
09:12:51 java.lang.ClassNotFoundException: com.atlassian.fugue.Effect
09:12:51 	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
09:12:51 	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1327)
09:12:51 	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1080)
09:12:51 	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357)
09:12:51 Caused: java.lang.NoClassDefFoundError: com/atlassian/fugue/Effect
09:12:51 	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.doCreate(DefaultHttpClientFactory.java:68)
09:12:51 	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.create(DefaultHttpClientFactory.java:35)
09:12:51 	at com.atlassian.jira.<span class="code-keyword">rest</span>.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:63)
09:12:51 	at com.atlassian.jira.<span class="code-keyword">rest</span>.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
09:12:51 	at com.atlassian.jira.<span class="code-keyword">rest</span>.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
09:12:51 	at hudson.plugins.jira.JiraSite.createSession(JiraSite.java:280)
09:12:51 	at hudson.plugins.jira.JiraSite.getSession(JiraSite.java:255)
09:12:51 	at hudson.plugins.jira.Updater.perform(Updater.java:95)
09:12:51 	at hudson.plugins.jira.JiraIssueUpdater.perform(JiraIssueUpdater.java:64)
09:12:51 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
09:12:51 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
09:12:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
09:12:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
09:12:51 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
09:12:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
09:12:51 	at hudson.model.Run.execute(Run.java:1760)
09:12:51 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
09:12:51 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:12:51 	at hudson.model.Executor.run(Executor.java:405)
</pre>
</div></div>
<p>Downgrading to 2.3.1 solves the issue.</p>

<p>Upgrading Jenkins to version 2.60.2 also solves the issue.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.60.1<br/>
JIRA plugin 2.4.2<br/>
JIRA v1001.0.0-SNAPSHOT
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>dastra:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-46060?focusedId=309803&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-309803">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>We have the same issue; downgrade to 2.3.0 worked here as well.   Our jenkins version is 2.73</p>
</pre>
</details>

</ul>
</details>

<p>We have the same issue; downgrade to 2.3.0 worked here as well.   Our jenkins version is 2.73</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/pholden.jpg" title="pholden's avatar" /> pholden:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-46060?focusedId=309882&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-309882">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Sounds like similar exception/stacktrace as reported in <a href="https://issues.jenkins.io/browse/JENKINS-45992" title="Cannot validate JIRA site settings" class="issue-link" data-issue-key="JENKINS-45992"><del>JENKINS-45992</del></a></p>
</pre>
</details>

</ul>
</details>

<p>Sounds like similar exception/stacktrace as reported in <a href="https://issue-redirect.jenkins.io/issue/45992" title="Cannot validate JIRA site settings" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/45992">JENKINS-45992</a>"><del>JENKINS-45992</del></a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>kskovbo:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-46060?focusedId=309900&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-309900">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Yes, it sounds like the same problem. I will resolve this issue as a duplicate.</p>
</pre>
</details>

</ul>
</details>

<p>Yes, it sounds like the same problem. I will resolve this issue as a duplicate.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/45992">JENKINS-45992</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/45992">JENKINS-45992</a>]</i>
