### ISSUE TITLE
[JENKINS-64148] Jira plugin: NoSuchMethodError: hudson.plugins.jira.JiraBuildAction.<init>(Lhudson/model/Run;Ljava/util/Set;)

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jira-plugin#1123]
<p>After upgrading jira-steps-plugin to 1.6.0 (also using latest blue ocean), the following exception occurs when using a jira step inside a workflow:</p>

<pre>
 java.lang.NoSuchMethodError: hudson.plugins.jira.JiraBuildAction.<init>(Lhudson/model/Run;Ljava/util/Set;)V
17:28:43  	at io.jenkins.blueocean.service.embedded.jira.JiraSCMListener.onChangeLogParsed(JiraSCMListener.java:64)
17:28:43  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onCheckout(WorkflowRun.java:876)
17:28:43  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$1000(WorkflowRun.java:137)
17:28:43  	at org.jenkinsci.plugins.workflow.job.WorkflowRun$SCMListenerImpl.onCheckout(WorkflowRun.java:1168)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
17:28:43  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:28:43  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:28:43  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:28:43  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:28:43  	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
</pre>

<p>rolling back jira-steps-plugin to 1.5.5 seems to fix the issue</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=juanpablo">juanpablo</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148" target="_blank">Jira plugin: NoSuchMethodError: hudson.plugins.jira.JiraBuildAction.<init>(Lhudson/model/Run;Ljava/util/Set;)</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/gmshake.svg" title="gmshake's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gmshake">gmshake</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: jira-plugin
<li><b>label(s)</b>: regression
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-11-06T13:48:19+00:00
<li><b>votes</b>: 4
<li><b>watchers</b>: 8
<li><b>imported</b>: 2025-12-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading jira-steps-plugin to 1.6.0 (also using latest blue ocean), the following exception occurs when using a jira step inside a workflow:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> java.lang.NoSuchMethodError: hudson.plugins.jira.JiraBuildAction.&lt;init&gt;(Lhudson/model/Run;Ljava/util/Set;)V
17:28:43  	at io.jenkins.blueocean.service.embedded.jira.JiraSCMListener.onChangeLogParsed(JiraSCMListener.java:64)
17:28:43  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onCheckout(WorkflowRun.java:876)
17:28:43  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$1000(WorkflowRun.java:137)
17:28:43  	at org.jenkinsci.plugins.workflow.job.WorkflowRun$SCMListenerImpl.onCheckout(WorkflowRun.java:1168)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
17:28:43  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
17:28:43  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:28:43  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:28:43  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:28:43  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:28:43  	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
</pre>
</div></div>

<p>rolling back jira-steps-plugin to 1.5.5 seems to fix the issue</p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
- _Remote link associated with this issue:_


  - [PR-299](https://github.com/jenkinsci/jira-plugin/pull/299)

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>fho:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400752&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400752">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>We have builds failing with the same error message but we do not have the jira-steps plugin installed.
 We have the "jira" (v. 3.1.2) and the "jira-blueocean" (v. 1.24.32 plugin installed though. Our  jenkins version is 2.264</p>

<p><del><sub>When I retrigger a job that failed with this issue, all restarted builds succeeded so far.</sub></del> (wrong)</p>

<p> </p>

<p>Update: Downgrading the Jira plugin to version 3.1.1 seem to have solved the issue.
 It might have been introduced with <a href="https://github.com/jenkinsci/jira-plugin/pull/283" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/pull/283</a></p>

<p> </p>

<p> </p>
</pre>
</details>

</ul>
</details>

<p>We have builds failing with the same error message but we do not have the jira-steps plugin installed.<br/>
 We have the "jira" (v. 3.1.2) and the "jira-blueocean" (v. 1.24.32 plugin installed though. Our  jenkins version is 2.264</p>

<p><del><sub>When I retrigger a job that failed with this issue, all restarted builds succeeded so far.</sub></del> (wrong)</p>

<p> </p>

<p>Update: Downgrading the Jira plugin to version 3.1.1 seem to have solved the issue.<br/>
 It might have been introduced with <a href="https://github.com/jenkinsci/jira-plugin/pull/283" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/pull/283</a></p>

<p> </p>

<p> </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>juanpablo:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400753&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400753">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Hi, after downgrading jira-steps-plugin we're still seeing the same stacktrace. Upon further examination, we came to the same conclusion as <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fho" class="user-hover" rel="fho">fho</a>, seems that downgrading jira-plugin to 3.1.1 does the trick, will update the issue to reflect that.</p>
</pre>
</details>

</ul>
</details>

<p>Hi, after downgrading jira-steps-plugin we're still seeing the same stacktrace. Upon further examination, we came to the same conclusion as <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fho" class="user-hover" rel="fho">fho</a>, seems that downgrading jira-plugin to 3.1.1 does the trick, will update the issue to reflect that.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/gmshake.svg" title="gmshake's avatar" /> gmshake:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400756&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400756">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Cross link github PR <a href="https://github.com/jenkinsci/jira-plugin/pull/299" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/pull/299</a>.</p>
</pre>
</details>

</ul>
</details>

<p>Cross link github PR <a href="https://github.com/jenkinsci/jira-plugin/pull/299" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/pull/299</a>.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>patriks:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400757&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400757">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Hi,</p>

<p>Also seeing this problem when upgraded to 2.265 and Jira plugin 3.1.2.</p>

<p>Downgrade Jira plugin to 3.1.1 seems to solve it for us too.</p>
</pre>
</details>

</ul>
</details>

<p>Hi,</p>

<p>Also seeing this problem when upgraded to 2.265 and Jira plugin 3.1.2.</p>

<p>Downgrade Jira plugin to 3.1.1 seems to solve it for us too.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>fho:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400761&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400761">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Thanks a lot for the fast response, <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gmshake" class="user-hover" rel="gmshake">gmshake</a>!</p>
</pre>
</details>

</ul>
</details>

<p>Thanks a lot for the fast response, <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gmshake" class="user-hover" rel="gmshake">gmshake</a>!</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/gmshake.svg" title="gmshake's avatar" /> gmshake:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400767&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400767">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Hi,</p>

<p>jira-plugin version 3.1.3 has been released, but there may be some delay on the update center. The release note:  <a href="https://github.com/jenkinsci/jira-plugin/releases/tag/jira-3.1.3" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/releases/tag/jira-3.1.3</a></p>
</pre>
</details>

</ul>
</details>

<p>Hi,</p>

<p>jira-plugin version 3.1.3 has been released, but there may be some delay on the update center. The release note:  <a href="https://github.com/jenkinsci/jira-plugin/releases/tag/jira-3.1.3" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/releases/tag/jira-3.1.3</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64148?focusedId=400809&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-400809">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Thanks <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gmshake" class="user-hover" rel="gmshake">gmshake</a>.  It is quite a delight to detect a failure in a job and discover that others have already detected it, the maintainer has resolved it, and a new plugin is released with the fix.  My sincere thanks for your rapid response to the issue!</p>
</pre>
</details>

</ul>
</details>

<p>Thanks <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gmshake" class="user-hover" rel="gmshake">gmshake</a>.  It is quite a delight to detect a failure in a job and discover that others have already detected it, the maintainer has resolved it, and a new plugin is released with the fix.  My sincere thanks for your rapid response to the issue!</p>
