### ISSUE TITLE
[JENKINS-62703] JIRA plugin NosuchMethod Errorhudson.plugins.jira.JiraSite.getSession()Lhudson/plugins/jira/JiraSession;

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jira-plugin#1118]
<p>After updating the plugin version to 3.1.0 we started seeing this error. </p>

<p>When we retrigger the pipeline, this error is not coming, This error is happening on builds which get triggered by a commit on Git repository. </p>

<p>java.lang.NoSuchMethodError: hudson.plugins.jira.JiraSite.getSession()Lhudson/plugins/jira/JiraSession;<br/>
 at io.jenkins.blueocean.service.embedded.jira.JiraSCMListener.onChangeLogParsed(JiraSCMListener.java:47)<br/>
 at org.jenkinsci.plugins.workflow.job.WorkflowRun.onCheckout(WorkflowRun.java:865)<br/>
 at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$1000(WorkflowRun.java:137)<br/>
 at org.jenkinsci.plugins.workflow.job.WorkflowRun$SCMListenerImpl.onCheckout(WorkflowRun.java:1157)<br/>
 at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150)<br/>
 at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)<br/>
 at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)<br/>
 at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>
 at java.lang.Thread.run(Thread.java:748)<br/>
Finished: FAILURE</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=vikaskoppi">vikaskoppi</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703" target="_blank">JIRA plugin NosuchMethod Errorhudson.plugins.jira.JiraSite.getSession()Lhudson/plugins/jira/JiraSession;</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olamy">olamy</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>component(s)</b>: jira-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-06-17T23:52:29+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-12-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After updating the plugin version to 3.1.0 we started seeing this error. </p>

<p>When we retrigger the pipeline, this error is not coming, This error is happening on builds which get triggered by a commit on Git repository. </p>

<p>java.lang.NoSuchMethodError: hudson.plugins.jira.JiraSite.getSession()Lhudson/plugins/jira/JiraSession;
 at io.jenkins.blueocean.service.embedded.jira.JiraSCMListener.onChangeLogParsed(JiraSCMListener.java:47)
 at org.jenkinsci.plugins.workflow.job.WorkflowRun.onCheckout(WorkflowRun.java:865)
 at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$1000(WorkflowRun.java:137)
 at org.jenkinsci.plugins.workflow.job.WorkflowRun$SCMListenerImpl.onCheckout(WorkflowRun.java:1157)
 at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150)
 at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
 at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
 at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins ver. 2.204.6<br/>
Jenkins JIRA PLugin : 3.1.0
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>vikaskoppi:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392825&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392825">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=warden" class="user-hover" rel="warden">warden</a> please check this</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=warden" class="user-hover" rel="warden">warden</a> please check this</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392828&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392828">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>ah yes crap. the last changes breaks blue-ocean integration <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/> </p>

<p> </p>
</pre>
</details>

</ul>
</details>

<p>ah yes crap. the last changes breaks blue-ocean integration <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/> </p>

<p> </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>marcj:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392829&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392829">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Also encountered this issue (also have Blue Ocean installed), rolling back fixed it. Let me know if you need any info from my install</p>
</pre>
</details>

</ul>
</details>

<p>Also encountered this issue (also have Blue Ocean installed), rolling back fixed it. Let me know if you need any info from my install</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392832&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392832">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=marcj" class="user-hover" rel="marcj">marcj</a> thanks but that's ok the fix is ezy</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=marcj" class="user-hover" rel="marcj">marcj</a> thanks but that's ok the fix is ezy</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392834&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392834">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>fixed by <a href="https://github.com/jenkinsci/jira-plugin/commit/608342e249c92dccadbe8142e88b82b0b9c7c310" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/commit/608342e249c92dccadbe8142e88b82b0b9c7c310</a></p>
</pre>
</details>

</ul>
</details>

<p>fixed by <a href="https://github.com/jenkinsci/jira-plugin/commit/608342e249c92dccadbe8142e88b82b0b9c7c310" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/commit/608342e249c92dccadbe8142e88b82b0b9c7c310</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392835&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392835">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>3.1.1 has been released.</p>

<p>Sorry for the issue.</p>
</pre>
</details>

</ul>
</details>

<p>3.1.1 has been released.</p>

<p>Sorry for the issue.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>marcj:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-62703?focusedId=392836&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-392836">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Many thanks for the quick fix!</p>
</pre>
</details>

</ul>
</details>

<p>Many thanks for the quick fix!</p>
