### ISSUE TITLE
[JENKINS-12044] JIRA Plugin doesn't work with latest version of Hudson 2.1.2

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jira-plugin#843]
<p>Using the latest JIRA plugin (1.29) doesn't work in the latest version of Hudson (2.1.2). With "Update relevant JIRA issues" checked in a job's config, if a commit occurs with a valid JIRA number, the build fails with this:</p>

<p>Updating ECOM-8428<br/>
FATAL: hudson.scm.ChangeLogSet$Entry.getCommitId()Ljava/lang/String;<br/>
java.lang.NoSuchMethodError: hudson.scm.ChangeLogSet$Entry.getCommitId()Ljava/lang/String;<br/>
	at hudson.plugins.jira.Updater.getRevision(Updater.java:263)<br/>
	at hudson.plugins.jira.Updater.submitComments(Updater.java:136)<br/>
	at hudson.plugins.jira.Updater.perform(Updater.java:91)<br/>
	at hudson.plugins.jira.JiraIssueUpdater.perform(JiraIssueUpdater.java:29)<br/>
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:36)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:630)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:608)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:584)<br/>
	at hudson.model.Build$RunnerImpl.post2(Build.java:159)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:553)<br/>
	at hudson.model.Run.run(Run.java:1391)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:145)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=bbrouwer">bbrouwer</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-12044" target="_blank">JIRA Plugin doesn't work with latest version of Hudson 2.1.2</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: jira-plugin
<li><b>label(s)</b>: plugin
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2011-12-12T10:25:15+00:00
<li><b>votes</b>: 2
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-12-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Using the latest JIRA plugin (1.29) doesn't work in the latest version of Hudson (2.1.2). With "Update relevant JIRA issues" checked in a job's config, if a commit occurs with a valid JIRA number, the build fails with this:</p>

<p>Updating ECOM-8428
FATAL: hudson.scm.ChangeLogSet$Entry.getCommitId()Ljava/lang/String;
java.lang.NoSuchMethodError: hudson.scm.ChangeLogSet$Entry.getCommitId()Ljava/lang/String;
	at hudson.plugins.jira.Updater.getRevision(Updater.java:263)
	at hudson.plugins.jira.Updater.submitComments(Updater.java:136)
	at hudson.plugins.jira.Updater.perform(Updater.java:91)
	at hudson.plugins.jira.JiraIssueUpdater.perform(JiraIssueUpdater.java:29)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:36)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:630)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:608)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:584)
	at hudson.model.Build$RunnerImpl.post2(Build.java:159)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:553)
	at hudson.model.Run.run(Run.java:1391)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:145)</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Hudson 2.1.2</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>x97mdr:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-12044?focusedId=156484&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156484">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Same thing happens for me here.  Anyone know if it works for an earlier version of Hudson?</p>
</pre>
</details>

</ul>
</details>

<p>Same thing happens for me here.  Anyone know if it works for an earlier version of Hudson?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/kutzi.jpg" title="kutzi's avatar" /> kutzi:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-12044?focusedId=156572&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156572">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm not sure if the JIRA plugin is supposed to be working with post-fork Hudson versions</p>
</pre>
</details>

</ul>
</details>

<p>I'm not sure if the JIRA plugin is supposed to be working with post-fork Hudson versions</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/kutzi.jpg" title="kutzi's avatar" /> kutzi:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-12044?focusedId=156574&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156574">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>According to the Wiki page the plugin needs Jenkins 1.405 (post-fork), so it cannot work with Hudson anymore.</p>
</pre>
</details>

</ul>
</details>

<p>According to the Wiki page the plugin needs Jenkins 1.405 (post-fork), so it cannot work with Hudson anymore.</p>
