### ISSUE TITLE
[JENKINS-53808] Binary compatibility broken between JIRA plugin 3.0.2 and Artifactory plugin 2.16.2

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jira-plugin#1062]
<p>Jira integration doesn't work within Artifactory plugin after update of Jira plugin to 3.0.2 After downgrade to 3.0.0 or disabling Jira integration in every job it works again.</p>

<p>When the SCM commit match the Jira issue pattern I get this</p>

```
FATAL: hudson.plugins.jira.JiraSite.existsIssue(Ljava/lang/String;)Z
java.lang.NoSuchMethodError: hudson.plugins.jira.JiraSite.existsIssue(Ljava/lang/String;)Z
 at org.jfrog.hudson.util.IssuesTrackerHelper.<init>(IssuesTrackerHelper.java:49)
 at org.jfrog.hudson.util.ExtractorUtils.getArtifactoryClientConfiguration(ExtractorUtils.java:183)
 at org.jfrog.hudson.util.ExtractorUtils.addBuilderInfoArguments(ExtractorUtils.java:147)
 at org.jfrog.hudson.maven3.extractor.MavenExtractorEnvironment.buildEnvVars(MavenExtractorEnvironment.java:139)
 at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:881)
 at hudson.maven.AbstractMavenBuild.getEnvironment(AbstractMavenBuild.java:57)
 at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:168)
 at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:634)
 at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
 at hudson.model.Run.execute(Run.java:1815)
 at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
 at hudson.model.ResourceController.execute(ResourceController.java:97)
 at hudson.model.Executor.run(Executor.java:429)

```

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mi_ko">mi_ko</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-53808" target="_blank">Binary compatibility broken between JIRA plugin 3.0.2 and Artifactory plugin 2.16.2</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olamy">olamy</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: jira-plugin
<li><b>label(s)</b>: jira-plugin-3.0.3, regression
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-09-27T10:39:45+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-12-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Jira integration doesn't work within Artifactory plugin after update of Jira plugin to 3.0.2 After downgrade to 3.0.0 or disabling Jira integration in every job it works again.</p>

<p>When the SCM commit match the Jira issue pattern I get this</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>FATAL: hudson.plugins.jira.JiraSite.existsIssue(Ljava/lang/String;)Z
java.lang.NoSuchMethodError: hudson.plugins.jira.JiraSite.existsIssue(Ljava/lang/String;)Z
 at org.jfrog.hudson.util.IssuesTrackerHelper.&lt;init&gt;(IssuesTrackerHelper.java:49)
 at org.jfrog.hudson.util.ExtractorUtils.getArtifactoryClientConfiguration(ExtractorUtils.java:183)
 at org.jfrog.hudson.util.ExtractorUtils.addBuilderInfoArguments(ExtractorUtils.java:147)
 at org.jfrog.hudson.maven3.extractor.MavenExtractorEnvironment.buildEnvVars(MavenExtractorEnvironment.java:139)
 at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:881)
 at hudson.maven.AbstractMavenBuild.getEnvironment(AbstractMavenBuild.java:57)
 at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:168)
 at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:634)
 at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
 at hudson.model.Run.execute(Run.java:1815)
 at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
 at hudson.model.ResourceController.execute(ResourceController.java:97)
 at hudson.model.Executor.run(Executor.java:429)
</pre>
</div></div></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
JIRA plugin 3.0.2<br/>
Artifactory plugin 2.16.2<br/>
Jenkins 2.138.1
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/oleg_nenashev.png" title="oleg_nenashev's avatar" /> oleg_nenashev:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-53808?focusedId=350212&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350212">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>CC <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olamy" class="user-hover" rel="olamy">olamy</a>. Most likely t is a Jira plugin issue</p>
</pre>
</details>

</ul>
</details>

<p>CC <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olamy" class="user-hover" rel="olamy">olamy</a>. Most likely t is a Jira plugin issue</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-53808?focusedId=350214&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350214">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>looks to be removed here <a href="https://github.com/jenkinsci/jira-plugin/commit/23a00c1cedaaa3d4b0b00ff8f1cdeece5053bc2c#diff-974b061f6eda1c5088eaa93c765904ed" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/commit/23a00c1cedaaa3d4b0b00ff8f1cdeece5053bc2c#diff-974b061f6eda1c5088eaa93c765904ed</a> </p>

<p>I agree it's a bit rough to break backward compat for a minor release...</p>

<p>but doesn't too hard about using?</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">getIssue(<span class="code-object">String</span> id) </pre>
</div></div>
<p> </p>
</pre>
</details>

</ul>
</details>

<p>looks to be removed here <a href="https://github.com/jenkinsci/jira-plugin/commit/23a00c1cedaaa3d4b0b00ff8f1cdeece5053bc2c#diff-974b061f6eda1c5088eaa93c765904ed" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/commit/23a00c1cedaaa3d4b0b00ff8f1cdeece5053bc2c#diff-974b061f6eda1c5088eaa93c765904ed</a> </p>

<p>I agree it's a bit rough to break backward compat for a minor release...</p>

<p>but doesn't too hard about using?</p>

<pre>
getIssue(<span class="code-object">String</span> id) </pre>
<p> </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-53808?focusedId=350215&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350215">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>anyway I will restore binary compat.</p>
</pre>
</details>

</ul>
</details>

<p>anyway I will restore binary compat.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olamy.jpg" title="olamy's avatar" /> olamy:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-53808?focusedId=350219&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-350219">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>pr <a href="https://github.com/jenkinsci/jira-plugin/pull/165" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/pull/165</a></p>
</pre>
</details>

</ul>
</details>

<p>pr <a href="https://github.com/jenkinsci/jira-plugin/pull/165" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jira-plugin/pull/165</a></p>
